# Config relating to the Lazygit UI
gui:
  # The number of lines you scroll by when scrolling the main window
  scrollHeight: 2
  # If true, capture mouse events.
  # When mouse events are captured, it's a little harder to select text: e.g. requiring you to hold the option key when on macOS.
  mouseEvents: true
  customIcons:
    filenames:
      "notes.md": {icon: "î·¢", color: "#FEDDEF"}
  showIcons: true
  # If true, show a random tip in the command log when Lazygit starts
  showRandomTip: true
  # Default size for focused window. Can be changed from within Lazygit with '+' and '_' (but this won't change the default).
  # One of: 'normal' (default) | 'half' | 'full'
  screenMode: normal
# Config relating to git
git:
  # If true, do not spawn a separate process when using GPG
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: diff-so-fancy
# Keybindings
keybinding:
  universal:
    quit: q
