[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/autojump"]
    type = "archive"
    url = "https://github.com/wting/autojump/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/you-should-use"]
    type = "archive"
    url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/joshua-afk/nvim-universal"
